extend type Mutation {
  """
  ✨ Insert a single `Article` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  article_insert(
    """
    Data object to insert into the table.
    """
    data: Article_Data!
  ): Article_KeyOutput! @fdc_generated(from: "Article", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Game` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  game_insert(
    """
    Data object to insert into the table.
    """
    data: Game_Data!
  ): Game_KeyOutput! @fdc_generated(from: "Game", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `GameLineup` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  gameLineup_insert(
    """
    Data object to insert into the table.
    """
    data: GameLineup_Data!
  ): GameLineup_KeyOutput! @fdc_generated(from: "GameLineup", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `GamePlay` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  gamePlay_insert(
    """
    Data object to insert into the table.
    """
    data: GamePlay_Data!
  ): GamePlay_KeyOutput! @fdc_generated(from: "GamePlay", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Player` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  player_insert(
    """
    Data object to insert into the table.
    """
    data: Player_Data!
  ): Player_KeyOutput! @fdc_generated(from: "Player", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `PlayerStats` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  playerStats_insert(
    """
    Data object to insert into the table.
    """
    data: PlayerStats_Data!
  ): PlayerStats_KeyOutput! @fdc_generated(from: "PlayerStats", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Schedule` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  schedule_insert(
    """
    Data object to insert into the table.
    """
    data: Schedule_Data!
  ): Schedule_KeyOutput! @fdc_generated(from: "Schedule", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Team` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  team_insert(
    """
    Data object to insert into the table.
    """
    data: Team_Data!
  ): Team_KeyOutput! @fdc_generated(from: "Team", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `TeamMember` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  teamMember_insert(
    """
    Data object to insert into the table.
    """
    data: TeamMember_Data!
  ): TeamMember_KeyOutput! @fdc_generated(from: "TeamMember", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Article` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  article_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Article_Data!]!
  ): [Article_KeyOutput!]! @fdc_generated(from: "Article", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Game` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  game_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Game_Data!]!
  ): [Game_KeyOutput!]! @fdc_generated(from: "Game", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `GameLineup` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  gameLineup_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [GameLineup_Data!]!
  ): [GameLineup_KeyOutput!]! @fdc_generated(from: "GameLineup", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `GamePlay` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  gamePlay_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [GamePlay_Data!]!
  ): [GamePlay_KeyOutput!]! @fdc_generated(from: "GamePlay", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Player` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  player_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Player_Data!]!
  ): [Player_KeyOutput!]! @fdc_generated(from: "Player", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `PlayerStats` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  playerStats_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [PlayerStats_Data!]!
  ): [PlayerStats_KeyOutput!]! @fdc_generated(from: "PlayerStats", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Schedule` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  schedule_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Schedule_Data!]!
  ): [Schedule_KeyOutput!]! @fdc_generated(from: "Schedule", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Team` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  team_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Team_Data!]!
  ): [Team_KeyOutput!]! @fdc_generated(from: "Team", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `TeamMember` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  teamMember_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [TeamMember_Data!]!
  ): [TeamMember_KeyOutput!]! @fdc_generated(from: "TeamMember", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Article` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Article`.
  """
  article_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Article_Data!
  ): Article_KeyOutput! @fdc_generated(from: "Article", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Game` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Game`.
  """
  game_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Game_Data!
  ): Game_KeyOutput! @fdc_generated(from: "Game", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `GameLineup` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `GameLineup`.
  """
  gameLineup_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: GameLineup_Data!
  ): GameLineup_KeyOutput! @fdc_generated(from: "GameLineup", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `GamePlay` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `GamePlay`.
  """
  gamePlay_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: GamePlay_Data!
  ): GamePlay_KeyOutput! @fdc_generated(from: "GamePlay", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Player` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Player`.
  """
  player_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Player_Data!
  ): Player_KeyOutput! @fdc_generated(from: "Player", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `PlayerStats` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PlayerStats`.
  """
  playerStats_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: PlayerStats_Data!
  ): PlayerStats_KeyOutput! @fdc_generated(from: "PlayerStats", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Schedule` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Schedule`.
  """
  schedule_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Schedule_Data!
  ): Schedule_KeyOutput! @fdc_generated(from: "Schedule", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Team` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Team`.
  """
  team_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Team_Data!
  ): Team_KeyOutput! @fdc_generated(from: "Team", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `TeamMember` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TeamMember`.
  """
  teamMember_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: TeamMember_Data!
  ): TeamMember_KeyOutput! @fdc_generated(from: "TeamMember", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Article` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Article`.
  """
  article_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Article_Data!]!
  ): [Article_KeyOutput!]! @fdc_generated(from: "Article", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Game` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Game`.
  """
  game_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Game_Data!]!
  ): [Game_KeyOutput!]! @fdc_generated(from: "Game", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `GameLineup` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `GameLineup`.
  """
  gameLineup_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [GameLineup_Data!]!
  ): [GameLineup_KeyOutput!]! @fdc_generated(from: "GameLineup", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `GamePlay` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `GamePlay`.
  """
  gamePlay_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [GamePlay_Data!]!
  ): [GamePlay_KeyOutput!]! @fdc_generated(from: "GamePlay", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Player` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Player`.
  """
  player_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Player_Data!]!
  ): [Player_KeyOutput!]! @fdc_generated(from: "Player", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `PlayerStats` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PlayerStats`.
  """
  playerStats_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [PlayerStats_Data!]!
  ): [PlayerStats_KeyOutput!]! @fdc_generated(from: "PlayerStats", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Schedule` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Schedule`.
  """
  schedule_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Schedule_Data!]!
  ): [Schedule_KeyOutput!]! @fdc_generated(from: "Schedule", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Team` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Team`.
  """
  team_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Team_Data!]!
  ): [Team_KeyOutput!]! @fdc_generated(from: "Team", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `TeamMember` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TeamMember`.
  """
  teamMember_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [TeamMember_Data!]!
  ): [TeamMember_KeyOutput!]! @fdc_generated(from: "TeamMember", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Article` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Article` or `null` if not found.
  """
  article_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Article_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Article_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Article_Data!
  ): Article_KeyOutput @fdc_generated(from: "Article", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Game` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Game` or `null` if not found.
  """
  game_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Game_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Game_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Game_Data!
  ): Game_KeyOutput @fdc_generated(from: "Game", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `GameLineup` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `GameLineup` or `null` if not found.
  """
  gameLineup_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: GameLineup_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GameLineup_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: GameLineup_Data!
  ): GameLineup_KeyOutput @fdc_generated(from: "GameLineup", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `GamePlay` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `GamePlay` or `null` if not found.
  """
  gamePlay_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: GamePlay_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GamePlay_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: GamePlay_Data!
  ): GamePlay_KeyOutput @fdc_generated(from: "GamePlay", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Player` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Player` or `null` if not found.
  """
  player_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Player_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Player_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Player_Data!
  ): Player_KeyOutput @fdc_generated(from: "Player", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `PlayerStats` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `PlayerStats` or `null` if not found.
  """
  playerStats_update(
    """
    The key used to identify the object.
    """
    key: PlayerStats_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlayerStats_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: PlayerStats_Data!
  ): PlayerStats_KeyOutput @fdc_generated(from: "PlayerStats", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Schedule` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Schedule` or `null` if not found.
  """
  schedule_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Schedule_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Schedule_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Schedule_Data!
  ): Schedule_KeyOutput @fdc_generated(from: "Schedule", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Team` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Team` or `null` if not found.
  """
  team_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Team_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Team_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Team_Data!
  ): Team_KeyOutput @fdc_generated(from: "Team", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `TeamMember` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `TeamMember` or `null` if not found.
  """
  teamMember_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TeamMember_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TeamMember_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: TeamMember_Data!
  ): TeamMember_KeyOutput @fdc_generated(from: "TeamMember", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Article` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  article_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Article_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Article_Data!
  ): Int! @fdc_generated(from: "Article", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Game` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  game_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Game_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Game_Data!
  ): Int! @fdc_generated(from: "Game", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `GameLineup` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  gameLineup_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: GameLineup_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: GameLineup_Data!
  ): Int! @fdc_generated(from: "GameLineup", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `GamePlay` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  gamePlay_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: GamePlay_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: GamePlay_Data!
  ): Int! @fdc_generated(from: "GamePlay", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Player` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  player_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Player_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Player_Data!
  ): Int! @fdc_generated(from: "Player", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `PlayerStats` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  playerStats_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: PlayerStats_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: PlayerStats_Data!
  ): Int! @fdc_generated(from: "PlayerStats", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Schedule` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  schedule_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Schedule_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Schedule_Data!
  ): Int! @fdc_generated(from: "Schedule", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Team` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  team_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Team_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Team_Data!
  ): Int! @fdc_generated(from: "Team", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `TeamMember` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  teamMember_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: TeamMember_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: TeamMember_Data!
  ): Int! @fdc_generated(from: "TeamMember", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Article` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  article_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Article_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Article_FirstRow
  ): Article_KeyOutput @fdc_generated(from: "Article", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Game` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  game_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Game_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Game_FirstRow
  ): Game_KeyOutput @fdc_generated(from: "Game", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `GameLineup` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  gameLineup_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: GameLineup_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GameLineup_FirstRow
  ): GameLineup_KeyOutput @fdc_generated(from: "GameLineup", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `GamePlay` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  gamePlay_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: GamePlay_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GamePlay_FirstRow
  ): GamePlay_KeyOutput @fdc_generated(from: "GamePlay", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Player` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  player_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Player_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Player_FirstRow
  ): Player_KeyOutput @fdc_generated(from: "Player", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `PlayerStats` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  playerStats_delete(
    """
    The key used to identify the object.
    """
    key: PlayerStats_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlayerStats_FirstRow
  ): PlayerStats_KeyOutput @fdc_generated(from: "PlayerStats", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Schedule` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  schedule_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Schedule_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Schedule_FirstRow
  ): Schedule_KeyOutput @fdc_generated(from: "Schedule", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Team` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  team_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Team_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Team_FirstRow
  ): Team_KeyOutput @fdc_generated(from: "Team", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `TeamMember` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  teamMember_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TeamMember_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TeamMember_FirstRow
  ): TeamMember_KeyOutput @fdc_generated(from: "TeamMember", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Article` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  article_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Article_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Article", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Game` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  game_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Game_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Game", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `GameLineup` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  gameLineup_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: GameLineup_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "GameLineup", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `GamePlay` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  gamePlay_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: GamePlay_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "GamePlay", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Player` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  player_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Player_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Player", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `PlayerStats` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  playerStats_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: PlayerStats_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "PlayerStats", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Schedule` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  schedule_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Schedule_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Schedule", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Team` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  team_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Team_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Team", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `TeamMember` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  teamMember_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: TeamMember_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "TeamMember", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
}
