extend type Query {
  """
  ✨ Look up a single `Article` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  article(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Article_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Article_FirstRow
  ): Article @fdc_generated(from: "Article", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Game` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  game(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Game_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Game_FirstRow
  ): Game @fdc_generated(from: "Game", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `GameLineup` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  gameLineup(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: GameLineup_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GameLineup_FirstRow
  ): GameLineup @fdc_generated(from: "GameLineup", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `GamePlay` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  gamePlay(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: GamePlay_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GamePlay_FirstRow
  ): GamePlay @fdc_generated(from: "GamePlay", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Player` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  player(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Player_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Player_FirstRow
  ): Player @fdc_generated(from: "Player", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `PlayerStats` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  playerStats(
    """
    The key used to identify the object.
    """
    key: PlayerStats_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlayerStats_FirstRow
  ): PlayerStats @fdc_generated(from: "PlayerStats", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Schedule` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  schedule(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Schedule_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Schedule_FirstRow
  ): Schedule @fdc_generated(from: "Schedule", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Team` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  team(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Team_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Team_FirstRow
  ): Team @fdc_generated(from: "Team", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `TeamMember` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  teamMember(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TeamMember_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TeamMember_FirstRow
  ): TeamMember @fdc_generated(from: "TeamMember", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `Article` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  articles(
    """
    Filter condition to narrow down the query results.
    """
    where: Article_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Article_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Article_Having
  ): [Article!]! @fdc_generated(from: "Article", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Game` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  games(
    """
    Filter condition to narrow down the query results.
    """
    where: Game_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Game_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Game_Having
  ): [Game!]! @fdc_generated(from: "Game", purpose: QUERY_MULTIPLE)
  """
  ✨ List `GameLineup` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  gameLineups(
    """
    Filter condition to narrow down the query results.
    """
    where: GameLineup_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [GameLineup_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: GameLineup_Having
  ): [GameLineup!]! @fdc_generated(from: "GameLineup", purpose: QUERY_MULTIPLE)
  """
  ✨ List `GamePlay` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  gamePlays(
    """
    Filter condition to narrow down the query results.
    """
    where: GamePlay_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [GamePlay_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: GamePlay_Having
  ): [GamePlay!]! @fdc_generated(from: "GamePlay", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Player` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  players(
    """
    Filter condition to narrow down the query results.
    """
    where: Player_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Player_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Player_Having
  ): [Player!]! @fdc_generated(from: "Player", purpose: QUERY_MULTIPLE)
  """
  ✨ List `PlayerStats` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  playerStatss(
    """
    Filter condition to narrow down the query results.
    """
    where: PlayerStats_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PlayerStats_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PlayerStats_Having
  ): [PlayerStats!]! @fdc_generated(from: "PlayerStats", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Schedule` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  schedules(
    """
    Filter condition to narrow down the query results.
    """
    where: Schedule_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Schedule_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Schedule_Having
  ): [Schedule!]! @fdc_generated(from: "Schedule", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Team` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  teams(
    """
    Filter condition to narrow down the query results.
    """
    where: Team_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Team_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Team_Having
  ): [Team!]! @fdc_generated(from: "Team", purpose: QUERY_MULTIPLE)
  """
  ✨ List `TeamMember` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  teamMembers(
    """
    Filter condition to narrow down the query results.
    """
    where: TeamMember_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TeamMember_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TeamMember_Having
  ): [TeamMember!]! @fdc_generated(from: "TeamMember", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
